@startuml
left to right direction
actor "Paciente" as Patient
actor "Dentista" as Dentist
actor "Recepcionista" as Receptionist

rectangle "Sistema de Clínica Dental" {
  usecase "Agendar cita" as UC1
  usecase "Cancelar cita" as UC2
  usecase "Realizar consulta" as UC3
  usecase "Realizar limpieza" as UC4
  usecase "Emitir receta" as UC5
  usecase "Generar factura" as UC6
  usecase "Actualizar historial médico" as UC7
}

Patient --> UC1
Patient --> UC2
Patient --> UC3
Patient --> UC4
Dentist --> UC3
Dentist --> UC4
Dentist --> UC5
Dentist --> UC7
Receptionist --> UC1
Receptionist --> UC2
Receptionist --> UC6
@enduml